### ISSUE TITLE
possible bug in gofasta sam toMultiAlign

### ISSUE THREAD

**Issue by rmcolq** [virus-evolution/gofasta#21]
Datapipe uses the following gofasta command:
```
gofasta sam toMultiAlign -t ${task.cpus} \
      --samfile ${sam} \
      --reference ${reference_fasta} \
      --pad \
      -o alignment.fasta
```
As reported on COG-UK slack, AY.4.2 on V3 primers often has amplicon 72 dropout (like all Delta), but also seems to have poor amplicon 73 performance (not entirely sure why). This sometimes results in low (say below 100) depth, but not below the 10x cut-off in the calling pipeline. So you get Y145H called in the consensus, at the very beginning of the amplicon 73. But something happens in the trim/pad step that seems to replace the first few bases in 73 with N, probably related to the nearby 6bp deletion.

For example, PLYM-205EBC0

consensus fasta in this area is:
CAACTCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGCTTCCANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTATCACCACAAAAACAACAAAAGTTGGATGGAAAGTGGAGTTTATTC

showing 72 dropped out, and then TTATC… at the begninning of 73

but the trimpad fasta is:
CAACTCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNACCACAAAAACAACAAAAGTTGGATGGAAAGTG------GAGTTTATTC

where it has correctly aligned the deletion to the ref, but replaced the small amount of non-N sequence in 72 with N’s, and also added five N’s to the beginning of 73
This seems like unexpected behaviour.
And what it results in is AY.4.2 without Y145H called, even though the consensus fasta supports it (the “T” at 21995, 5bp into amplicon 73)

**Comment by jcbarret** [comment]
[Archive.zip](https://github.com/cov-ert/gofasta/files/7380337/Archive.zip)
Here's a zip of the input and output fastas.

**Comment by jcbarret** [comment]
Yeah, latest version is 2.22, so I suspect it is something that was introduced at some point...and it also looks like it surprised the poster of that issue. Could try running with --score-N=0 on a bunch of alignments and see what changes?
