### ISSUE TITLE
Error: empty fasta file   

### ISSUE THREAD

**Issue by Jinke233** [virus-evolution/gofasta#38]
/public/home/bgi_dujinke/software/gofasta  snps -r /public/home/bgiadmin/Project/F21FTSNCKF3685/PLAwxtzD/F22FTSCCKF9331_BAConxtD_tenbacteria/01_canu/ZFSD027-F5B/ZFSD027-F5B.contigs.fasta.format_v2 -q /public/home/bgiadmin/Project/F21FTSNCKF3685/PLAwxtzD/F22FTSCCKF9331_BAConxtD_tenbacteria/01_canu/muscle/output/all_ZFSD027_query.fas.aln_v2 -o snps.csv
Error: empty fasta file

This is my error. I guess that it is the porblem about reading fasta file.

**Comment by benjamincjackson** [comment]
Hi. You could try this again with the latest version (`1.2.0`) and see if it was fixed when I fixed #37?
