### ISSUE TITLE
Question: Does gofasta ignore SNPs in the first 16 nt of a sequence?

### ISSUE THREAD

**Issue by mmokrejs** [virus-evolution/gofasta#49]
https://github.com/virus-evolution/gofasta/blob/f80b54427556e70c34ea7df471dbcb2a3b5760af/pkg/variants/pairwise.go#L78

**Comment by bjeight** [comment]
Hi.

The pseudocode: `reference nucleotide & query nucleotide < 16` represents a bitwise operation to check for a certain nucleotide difference between reference and query. 

Internally, gofasta encodes nucleotide sequences using Emmanual Paradis' bitwise coding scheme, which is used in the R package ape. This makes for fast sequence comparison.

The code excerpt you paste above is what this ends up looking like in the program. It does *not* represent a check for the position of the nucleotide in the alignment, so in answer to your question, no, gofasta does not ignore SNPs in the first 16 nucleotides of a sequence.

Unfortunately the ape website seems to be broken/down at the moment, but usually you can find a description of the scheme here: [http://ape-package.ird.fr/misc/BitLevelCodingScheme.html](http://ape-package.ird.fr/misc/BitLevelCodingScheme.html)

**Comment by benjamincjackson** [comment]
Hi.

The pseudocode: `reference nucleotide & query nucleotide < 16` represents a bitwise operation to check for a certain nucleotide difference between reference and query.

Internally, gofasta encodes nucleotide sequences using Emmanual Paradis' bitwise coding scheme, which is used in the R package ape. This makes for fast sequence comparison.

The code excerpt you paste above is what this ends up looking like in the program. It does not represent a check for the position of the nucleotide in the alignment, so in answer to your question, no, gofasta does not ignore SNPs in the first 16 nucleotides of a sequence.

Unfortunately the ape website seems to be broken/down at the moment, but usually you can find a description of the scheme here: [http://ape-package.ird.fr/misc/BitLevelCodingScheme.html](http://ape-package.ird.fr/misc/BitLevelCodingScheme.html)
